// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVllStvt383d2RK8v9zI5-Dg7q1oJe2ic',
    appId: '1:708185982496:web:4fa3d7ae277c80e9545e45',
    messagingSenderId: '708185982496',
    projectId: 'boa-waste-collector',
    authDomain: 'boa-waste-collector.firebaseapp.com',
    databaseURL: 'https://boa-waste-collector-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'boa-waste-collector.appspot.com',
    measurementId: 'G-C62S09ZM7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-2VL4RKjcbIP8QumNMbEmystmguPdj4o',
    appId: '1:708185982496:android:a7be16afdec4fafc545e45',
    messagingSenderId: '708185982496',
    projectId: 'boa-waste-collector',
    databaseURL: 'https://boa-waste-collector-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'boa-waste-collector.appspot.com',
  );
}
